### ISSUE TITLE
Suggestion: premium content switch

### ISSUE THREAD

**Issue by gwillingham0** [getignited/avengersacademy-tracker#1]
I think it would be good to have a switch to change between f2p to p2p so that if a person is not planning on purchasing premium characters they can prevent them from showing up in the total material requirements without having to check them off individually. It could also potentially hide them from the list so it doesn't get cluttered for f2p players as there will eventually be up to 4 premium characters with potentially 5 levels each.

**Comment by LiteMorgan** [comment]
Hey dude, thanks for the suggestion. I've started work on it, and hoping to get it live this weekend!
