### ISSUE TITLE
Problema with the check list.

### ISSUE THREAD

**Issue by Diegobpiquer** [getignited/avengersacademy-tracker#5]
Loved the list, extremely useful. But I have a big problem: Since the last update, whenever I check something of the list, it doesn't remove its requirements of the materials list, making the hole list kind of useles. I'm on mobile btw.

**Comment by LiteMorgan** [comment]
Finally had a chance to look over this and have found the issue. Please try clearing cache (or refreshing a few times!) and the list should be counting once again.
